services:
  alpine:
    container_name: boilerplate-alpine
    build:
      context: alpine
      tags:
        - cpuchalver/boilerplate:alpine
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./app:/app

  debian:
    container_name: boilerplate-debian
    build:
      context: debian
      tags:
        - cpuchalver/boilerplate:debian
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./app:/app

networks:
  boilerplate:
    name: boilerplate
