name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        id: setup
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            cpuchalver/alpine
            cpuchalver/debian
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Test
        run: |
          echo ${{ steps.metadata.outputs.tags }}
