name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        id: setup
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            cpuchalver/${{ matrix.target }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          bake-target: ${{ matrix.target }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        uses: docker/bake-action@v4
        with:
          targets: ${{ matrix.target }}
          files: |
            docker-compose.yml
          push: false
          # set: |
          #   target.tags=${{ steps.metadata.outputs.tags }}
