name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and export to Docker
        id: export
        uses: docker/bake-action@v4
        with:
          load: true
          set: |
            tags="test"

      - name: Test
        run: |
          docker run --rm test
          
      - name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true
          no-cache: true